mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bfh.mdm.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  datasource:
    tt:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tt?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 8
      max-idle: 8
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 1800000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
    tt2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tt2?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 8
      max-idle: 8
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 1800000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  file: log.txt
  level:
    com.zdpower: debug
